---
- name: create message of the day
  gather_facts: true #Explain this is not needed as the default is True, it is needed for the below fact.
  hosts: all
  become: true
  tasks:
  - name: edit message of the day file
    lineinfile:
      path: /etc/motd
      state: present
      line: 'This is my server on {{ ansible_default_ipv4.address }}'
